posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.main, name='main'),
    path('host/', views.host, name='host'),
    path('regist/', views.regist, name='regist'),
    path('lists/', views.lists, name='lists'),
    path('<int:cafe_id>/', views.detail, name='detail'),
    path('image/', views.image, name='image'),
    path('rcmd/', views.rcmd, name='rcmd'),
    path('create/', views.create, name='create'),
    path('<int:cafe_id>/review', views.review, name='review'),
    path('mypage/', views.mypage, name='mypage'),
    path('like/<int:cafe_id>/',views.like, name='like'),
    path('mark/<int:cafe_id>/',views.mark, name="mark"),
    path('mypage/markedcafe/', views.marked_cafe, name='markedcafe'),
    path('mypage/mysetting/', views.mysetting, name='mysetting'),
    path('mypage/version/', views.version, name='version'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=20, null=True)

    def __str__(self):
        return f'{self.name}'


class Cafe(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=20, null=True)
    address = models.CharField(max_length=100, null=True)
    open_time = models.TimeField(null=True)
    close_time = models.TimeField(null=True)
    holiday = models.CharField(max_length=50, null=True)
    tel = models.CharField(max_length=50, null=True)
    tags = models.ManyToManyField(Tag)
    memo = models.TextField(null=True)

    liked_users = models.ManyToManyField(User, related_name='like_cafe', blank=True)
    marked_users = models.ManyToManyField(User, related_name="marked_cafe", blank=True)


    def __str__(self):
        return f'{self.name}: {self.address}: {self.open_time}: {self.close_time}: {self.holiday}: {self.tel}'


class Image(models.Model):
    cafe = models.ForeignKey(Cafe, on_delete=models.CASCADE, null=False)
    image = models.ImageField(upload_to='posts', null=True)

posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.serializers import serialize
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from .models import Cafe, Tag, Image
from django.views.generic.base import View
from urllib.parse import urlparse
import json
import requests
import datetime
 
# 카카오 API 맵 
def getLatLng(address):
    result = ""
 
    url = 'https://dapi.kakao.com/v2/local/search/address.json?query=' + address
    rest_api_key = 'd975e180da8e3f1265e42a90c8ca1875'
    header = {'Authorization': 'KakaoAK ' + rest_api_key}
 
    r = requests.get(url, headers=header)
 
    if r.status_code == 200:
        result_address = r.json()["documents"][0]["address"]
        
        result = result_address["y"], result_address["x"]
    else:
        result = "ERROR[" + str(r.status_code) + "]"
    
    return result
 
 
def getKakaoMapHtml(address_latlng):
    javascript_key = "45522189c1ececf745d0f4c8c482b82e"
 
    result = ""
    result = result + "<div id='map' style='width:300px;height:200px;display:inline-block;'></div>" + "\n"
    result = result + "<script type='text/javascript' src='//dapi.kakao.com/v2/maps/sdk.js?appkey=" + javascript_key + "'></script>" + "\n"
    result = result + "<script>" + "\n"
    result = result + "    var container = document.getElementById('map'); " + "\n"
    result = result + "    var options = {" + "\n"
    result = result + "           center: new kakao.maps.LatLng(" + address_latlng[0] + ", " + address_latlng[1] + ")," + "\n"
    result = result + "           level: 3" + "\n"
    result = result + "    }; " + "\n"
    result = result + "    var map = new kakao.maps.Map(container, options); " + "\n"
    
    # 검색한 좌표의 마커 생성을 위해 추가
    result = result + "    var markerPosition  = new kakao.maps.LatLng(" + address_latlng[0] + ", " + address_latlng[1] + ");  " + "\n"
    result = result + "    var marker = new kakao.maps.Marker({position: markerPosition}); " + "\n"
    result = result + "    marker.setMap(map); " + "\n"
 
    result = result + "</script>" + "\n"
    
    return result
 
# main()
if __name__ == "__main__":
    address = "서울 강남구 선릉로 669"
    
    # 카카오 REST API로 좌표 구하기
    address_latlng = getLatLng(address)
 
    # 좌표로 지도 첨부 HTML 생성
    if str(address_latlng).find("ERROR") < 0:
        map_html = getKakaoMapHtml(address_latlng)
        
        print(map_html)
    else:
        print("[ERROR]getLatLng")




#-------------------------카카오맵--------------------
 

def main(request):
    total = Cafe.objects.annotate(num_tags=Count('tags')).filter(num_tags__gt=1).count()
    cafes = Cafe.objects.annotate(num_tags=Count('tags')).filter(num_tags__gt=1).order_by('-num_tags', 'id')[:4]
    context = {
        'total': total,
        'cafes': cafes,
        'tab': 'home',
    }
    return render(request, 'posts/main.html', context)


def rcmd(request):
    num = int(request.GET['num']) - 1
    offset = int(request.GET['offset'])
    cafes = Cafe.objects.annotate(num_tags=Count('tags')).filter(num_tags__gt=1).order_by('-num_tags', 'id')[num: num + offset]
    if cafes:
        cafes = serialize('json', cafes)
        cafes = json.loads(cafes)
        cafes = list(map(lambda cafe: {'id': cafe["pk"], **cafe["fields"]}, cafes))
        context = {
            'result': True,
            'cafes': cafes,
        }
    else:
        context = { 'result': False }
    return HttpResponse(json.dumps(context), content_type="application/json")


def host(request):
    return render(request, 'posts/host.html')


def regist(request):
    name = request.POST['name']
    tel = request.POST['tel']
    address = request.POST['address'] + ' ' + request.POST['detailAddress']
    ot = datetime.time(hour=int(request.POST['openTime']))
    ct = datetime.time(hour=int(request.POST['closeTime']))
    holiday = request.POST['holiday']
    body = request.POST['body']
    cafe = Cafe(name=name, memo=body, address=address, open_time=ot, close_time=ct, holiday=holiday, tel=tel)
    cafe.save()

    if 'image[]' in request.FILES:
        images = request.FILES.getlist('image[]')
        for image in images:
            img = Image(cafe=cafe, image=image)
            img.save()

    tags = request.POST['tags'].split(",")
    if len(tags) > 0 and tags[0]:
        for tag in tags:
            taged = Tag.objects.filter(name=tag).first()
            cafe.tags.add(taged.id)

    return redirect('posts:main')


def lists(request):

    page = 1
    offset = 4

    if 'page' in request.GET.keys():
        page = int(request.GET['page'])

    if 'offset' in request.GET.keys():
        offset = int(request.GET['offset'])

    num = (page - 1) * offset

    keywords = []

    if 'keywords[]' in request.GET.keys():
        keywords = request.GET.getlist('keywords[]')

        keyword = keywords.pop()
        cafes = Cafe.objects.filter(tags__name=keyword)

        for keyword in keywords:
            cafes = cafes.filter(tags__name=keyword)

        cafes = cafes.order_by('-id')[num: num + offset]
    else:
        cafes = Cafe.objects.all().order_by('-id')[num: num + offset]

    if request.is_ajax():
        cafes = serialize('json', cafes)
        cafes = json.loads(cafes)
        cafes = list(map(lambda cafe: {'id': cafe["pk"], **cafe["fields"]}, cafes))
        return HttpResponse(json.dumps({"cafes": cafes, "user": request.user.pk}), content_type="application/json")

    return render(request, 'posts/lists.html', {"cafes": cafes, 'tab': 'search'})

def detail(request, cafe_id):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    try:
        cafe = Cafe.objects.get(id=cafe_id)

        return render(request, 'posts/m-detail.html', { "cafe": cafe })

    except Cafe.DoesNotExist:
        pass

    return redirect('posts:lists')


def image(request):
    cafe = request.GET['cafe']
    
    if 'main' in request.GET.keys():
        image = Image.objects.filter(cafe=cafe).first()
        if image:
            imageurl = image.image.url
        return HttpResponse(json.dumps({"image": imageurl}), content_type="application/json")
    
    images = Image.objects.filter(cafe=cafe)
    if images:
        imageurls = []
        for image in images:
            imageurls.append(image.image.url)
    return HttpResponse(json.dumps({"images": imageurls}), content_type="application/json")


def review(request, cafe_id):
    return render(request, 'posts/review.html')

def create(request):
    return redirect('posts:main')

def mypage(request):
    return render(request, 'posts/mypage.html', {'tab': 'profile'})

def marked_cafe(request):
    # cafes = []
    cafes = request.user.marked_cafe.all()
    
    return render(request, 'posts/mypage/markedcafe.html', { "cafes": cafes })

def mysetting(request):
    return render(request, 'posts/mypage/mysetting.html')

def version(request):
    return render(request, 'posts/mypage/version.html')


@login_required
def like(request, cafe_id):

    try:
        cafe = Cafe.objects.get(id=cafe_id)

        if request.user in cafe.liked_users.all():
            cafe.liked_users.remove(request.user)
        else:
            cafe.liked_users.add(request.user)
            
        if 'next' in request.GET.keys():
            next = request.GET['next']
            return redirect(next)

        return redirect('posts:detail', cafe_id=cafe.id)

    except Cafe.DoesNotExist:
        pass

    return redirect('posts:main')

@login_required
def mark(request, cafe_id):

    try:
        cafe = Cafe.objects.get(id=cafe_id)

        if request.user in cafe.marked_users.all():
            cafe.marked_users.remove(request.user)
        else:
            cafe.marked_users.add(request.user)

        if 'next' in request.GET.keys():
            next = request.GET['next']
            return redirect(next)

        return redirect('posts:detail', cafe_id=cafe.id)

    except Cafe.DoesNotExist:
        pass

    return redirect('posts:main')

posts/templates/posts/mypage/markedcafe.html
{% extends "base.html" %}
{% load static %}
{% load socialaccount %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'posts/css/markedcafe.css' %}">
    <link rel="stylesheet" href="{% static 'posts/css/lists.css' %}">
    <!-- Link Swiper's CSS -->
    <link
      rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />

{% endblock %}
{% block script %}
<script src="{% static 'posts/js/mark.js' %}"></script>
{% endblock %}
{% block content %}
    
    {% block header %}
    {% include "header.html" %}
    {% endblock %}

    
    <div class="mypage-wrap">

    <section class="markedcafe">
        <div class="profile">
            <img src="{% static 'posts/images/icon/user.png' %}">
            <div class="profile-name">{{user.username}}님</div>
        </div>
        <hr>
        
        <h1>가고싶은 카페</h1>
        <hr>
        
        <!-- list -->
        {% if cafes %}
        <div class="filter-bg">
            <section class="filter-wrap">
                <ul class="filter-list">
                    {% for cafe in cafes %}
                    <li class="filter-item">
                        <a href="{% url 'posts:detail' cafe.id %}" class="filter">
                            <div class="filter-content">
                                <div class="filter-img">
                                    <!-- Swiper -->
                                    <div class="swiper-container">
                                      <div class="swiper-wrapper">
                                        {% for img in cafe.image_set.all %}
                                          <div class="swiper-slide">
                                              <img src="{{ img.image.url }}">
                                          </div>
                                        {% endfor %}
                                      </div>
                                    </div>
                                    <!-- {% if cafe.image_set.first %}
                                    <img src="{{ cafe.image_set.first.image.url }}">
                                    {% else %}
                                    <img src="{% static 'posts/images/logo-2.png' %}">
                                    {% endif %} -->
                                </div>
                                <div class="filter-text">
                                    {% if user.is_authenticated %}
                                        <div class="btn-wrap" data-cafe="{{ cafe.id }}">
                                            <span class="action-btn like-btn">
                                                {% if user in cafe.liked_users.all %}
                                                    <img src="{% static 'posts/images/icon/liked.png' %}">
                                                {% else %}
                                                    <img src="{% static 'posts/images/icon/like.png' %}">
                                                {% endif %}
                                            </span>
                                            
                                            
                                          <!-- If we need pagination -->
                                          <div class="swiper-pagination cafe-img-list"></div>

                                            <span class="action-btn btn mark-btn">
                                                {% if user in cafe.marked_users.all %}
                                                    <img src="{% static 'posts/images/icon/marked.png' %}">
                                                {% else %}
                                                    <img src="{% static 'posts/images/icon/mark.png' %}">
                                                {% endif %}
                                            </span>
                                        </div>
                                    {% endif %}
                                    <div class="info">
                                        <span>{{ cafe.name }}</span>
                                    </div>
                                    <div class="etc">
                                        {{ cafe.address }}
                                    </div>
                                </div>
                            </div>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </section>
        </div>

        <!-- Swiper JS -->
        <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

        <!-- Initialize Swiper -->
        <script>
          var swiper = new Swiper(".swiper-container", {
              slidesPerView: 'auto',
              // Optional parameters
              direction: 'horizontal',
              // loop: true,
              
              // If we need pagination
              pagination: {
                el: '.swiper-pagination',
              },

          });
        </script>
        
        {% else %}
        <div class="empty-list">
            <p class="empty-text">
                가고싶은 카페를 저장해보세요.
            </p>
            <a href="{% url 'posts:lists' %}" class="cafe-btn">카페 둘러보기</a>
        </div>

        {% endif %}
        <!-- !list -->
        

    </section>

    </div>

{% endblock %}

posts/templates/posts/mypage/mysetting.html
{% extends "base.html" %}
{% load static %}
{% load socialaccount %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}">

    <link rel="stylesheet" href="{% static 'posts/css/mypage.css' %}">
{% endblock %}
{% block content %}
    
    {% block header %}
    {% include "header.html" %}
    {% endblock %}

    {% csrf_token %}

    <div class="mypage-wrap">

    <section class="mypage">
        
        <h1>설정</h1>
        <hr>
        
        <h2>공지사항</h2>

        <h2><a href="{% url 'posts:version' %}">버전정보</a></h2>
        <hr>

        <h2>푸시 알림</h2>
        <div class="container">
            <div class="btn-toggle">
                <div class="inner-cc"></div>
            </div>
        </div>



        <h4>취향에 맞는 새로운 카페 정보를 보내드립니다.</h4>
        <h2>마케팅 수신 동의</h2>
        <h4>다양한 카페정보와 혜택을 담은 마케팅 정보를 SMS 및 이메일로 보내드립니다.</h4>
        <hr>
        
        <h2>고객센터</h2>

        
     

    </section>

    </div>

{% endblock %}

posts/templates/posts/mypage/version.html
{% extends "base.html" %}
{% load static %}
{% load socialaccount %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'posts/css/mypage.css' %}">
{% endblock %}
{% block content %}
    
    {% block header %}
    {% include "header.html" %}
    {% endblock %}

    {% csrf_token %}

    <div class="mypage-wrap">

    <section class="mypage">
        
        <h1>버전정보</h1>
        <hr>
        
        <h2>최신 버전을 사용중입니다</h2>
     

    </section>

    </div>
{% endblock %}