accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
		path('signup/', views.signup, name='signup'),
		path('login/', views.login, name='login'),
        path('logout/', views.logout, name='logout'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.main, name='main'),
    path('host/', views.host, name='host'),
    path('regist/', views.regist, name='regist'),
    path('lists/', views.lists, name='lists'),
    path('<int:cafe_id>/', views.detail, name='detail'),
    path('image/', views.image, name='image'),
    path('rcmd/', views.rcmd, name='rcmd'),
    path('create/', views.create, name='create'),
    path('<int:cafe_id>/review', views.review, name='review'),
    path('mypage/', views.mypage, name='mypage'),
    path('like/<int:cafe_id>/',views.like, name='like'),
    path('mark/<int:cafe_id>/',views.mark, name="mark"),
    path('mypage/markedcafe/', views.marked_cafe, name='markedcafe'),
    path('mypage/mysetting/', views.mysetting, name='mysetting'),
    path('mypage/version/', views.version, name='version'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko" dir="ltr">
  <head>
    <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cofflix</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/bottom.css' %}">
		{% block css %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="{% static 'js/header.js' %}"></script>
        {% block script %}
        {% endblock %}
  </head>
  <body>
    <div id="wrap">
		{% block header %}
        {% endblock %}
		{% block content %}
		{% endblock %}
    {% block bottom %}
    {% include "bottom.html" %}
    {% endblock %}
		</div>
		<!-- footer -->
		<footer id="footer">
			<div class="footer-inner">
				<p>Copyright © 2020 cofflix.co.,Ltd. All rights reserved.</p>
				<address>Contact webmaster for more information. 070-1234-5678</address>
			</div>
		</footer>
		<!-- !footer -->
  </body>
</html>

templates/bottom.html
{% load static %}
{% load socialaccount %}
<div class="bottom">
    {% if user.is_authenticated %}
    <a class="bottom-list" href="{% url 'posts:mypage' %}">
        <div class="bottom-img">
            {% if tab and tab == 'profile' %}
            <img src="{% static 'images/profile-on.svg' %}">
            {% else %}
            <img src="{% static 'images/profile.svg' %}">
            {% endif %}
        </div>
        <div class="bottom-text">
            마이페이지
        </div>
    </a>
    {% else %}
    <a class="bottom-list" href="{% url 'accounts:login' %}">
        <div class="bottom-img">
            <img src="{% static 'images/profile.svg' %}">
        </div>
        <div class="bottom-text">
            마이페이지
        </div>
    </a>
    {% endif %}
    <a class="bottom-list" href="{% url 'posts:main' %}">
        <div class="bottom-img">
            {% if tab and tab == 'home' %}
            <img src="{% static 'images/home-on.svg' %}">
            {% else %}
            <img src="{% static 'images/home.svg' %}">
            {% endif %}
        </div>
        <div class="bottom-text">
            홈
        </div>
    </a>
    <a class="bottom-list" href="{% url 'posts:lists' %}">
        <div class="bottom-img">
            {% if tab and tab == 'search' %}
            <img src="{% static 'images/search-on.svg' %}">
            {% else %}
            <img src="{% static 'images/search.svg' %}">
            {% endif %}
        </div>
        <div class="bottom-text">
            카페찾기
        </div>
    </a>
</div>

templates/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/category.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.css" integrity="sha512-IJEbgDEF7OeKJRa0MY2PApnyJHRIsgzCveek4ec8VWQ+7KG3ZSKVNYa5xP/Gh0hVP0Mwb+gBsk+GwR3JQGhQNg==" crossorigin="anonymous" />
</head>
<body>
    <div id="wrap">
        
         <!-- Header Start  -->
        <div class="header">
            <div class="header_control">
                <ul class="header_menu">
                    <li>
                        <a href="#">
                            <img class="main_logo" src="/icon/cofflixLogo.png" alt="logo">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            shop
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            review
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            cs
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            story
                        </a>
                    </li>
                </ul>
            </div>          
        </div>
        <!-- Header End  -->
        
        <!-- Container Start  -->
        <div class="container">
            <div class="filter_box">
                <div class="filter_top_control">
                    <form name="form_list" id="form_list" action="#">
                        <input type="hidden" name="sort" value>
                        <input type="hidden" name="sno" value=8>
                        <input type="hidden" name="search" value=y>
                        <div class="filter_top">
                            <div class="inner">
                                <div class="filter_select_view">
                                    <span class="filter_title">cafe</span>
                                    <button class="top_arrow_btn">></button>
                                    <span class="filter_text">search</span>
                                </div>
                                <div class="filter_text_search"></div>
                                <a href="#" class="btn_filter">
                                    <span>필터닫기</span>
                                </a>
                            </div>
                        </div>
                        <div class="filter_bottom" style="display: block">
                            <div class="inner">
                                <div class="filter_title_bottom">* 카테고리 별로 중복체크가능</div>
                                <dl class="all_filter_dl">
                                    <dt>
                                        <label class="checkcontainer" for="allcategory">
                                            <input type="checkbox" id="allcategory" checked>
                                            <p class="mot3">전체분류</p>
                                            
                                        </label>
                                    </dt>
                                </dl>
                                <dl class="filter_dl_cate001">
                                    <dt><p>Category</p></dt>
                                    <div class="category_box"></div>
                                    <dd>
                                        <label class="checkcontainer" for="category001">
                                            <input type="checkbox" id="category001" name="goodstype[]" value="001" data-cate-nm="시그니처">
                                            <span>#테라스</span>
                                            
                                        </label>
                                        <label class="checkcontainer" for="category002">
                                            <input type="checkbox" id="category002" name="goodstype[]" value="002" data-cate-nm="시그니처">
                                            <span>#드립전문</span>
                                            
                                        </label>
                                        <label class="checkcontainer" for="category003">
                                            <input type="checkbox" id="category003" name="goodstype[]" value="003" data-cate-nm="시그니처">
                                            <span>#로스팅</span>
                                            
                                        </label>
                                        <label class="checkcontainer" for="category004">
                                            <input type="checkbox" id="category004" name="goodstype[]" value="004" data-cate-nm="시그니처">
                                            <span>#애견동반</span>
                                           
                                        </label>
                                        <label class="checkcontainer" for="category005">
                                            <input type="checkbox" id="category005" name="goodstype[]" value="005" data-cate-nm="시그니처">
                                            <span>#작업하기좋은</span>
                                            
                                        </label>
                                        <label class="checkcontainer" for="category006">
                                            <input type="checkbox" id="category006" name="goodstype[]" value="006" data-cate-nm="시그니처">
                                            <span>#루프탑</span>
                                            
                                        </label>
                                        <label class="checkcontainer" for="category007">
                                            <input type="checkbox" id="category007" name="goodstype[]" value="007" data-cate-nm="시그니처">
                                            <span>#야간영업</span>
                                            
                                        </label>
                                        <label class="checkcontainer" for="category008">
                                            <input type="checkbox" id="category008" name="goodstype[]" value="008" data-cate-nm="시그니처">
                                            <span>#테이크아웃</span>
                                            
                                        </label>
                                    </dd>
                                </dl>
                                <button class="btn_select_mot3">선택 카테고리</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
         <!-- Container End  -->
        
         <!-- Design Top Start -->
   
   
        <!-- Design Top End -->

         <!-- Container_list_line Start  -->
  
        <div class="container_list_line">          
            <div class="container_list_line_control">
                <span class="list_line_review">리뷰순</span>
                <span class="list_line_recent">최신순</span>
            </div>
        </div>  
   
          <!-- Container_pick_list_line End  -->

         <!-- Container_list_img Start  -->
        <div class="container_list_img">
            <div class="container_pick_list_img"></div>
        </div>
         <!-- Container_list_img End -->

       
        <!-- Cotainer_item_list Start  -->
   
        <div class="cotainer_item_list">
            
            <div class="container_item_cont">
                <div class="container_item_type">
                    <ul>
                        <li>
                            <div class="container_item_cont_list">
                                <div class="container_item_photo_box_01">
                                    <a href="#">
                                        <div class="mot01"></div>
                                    </a>
                                </div>
                                <div class="container_item_info_01"></div>

                                <div class="container_item_photo_box_01">
                                    <a href="#">
                                        <div class="mot01"></div>
                                    </a>
                                </div>
                                <div class="container_item_info_01"></div>

                                <div class="container_item_photo_box_01">
                                    <a href="#">
                                        <div class="mot01"></div>
                                    </a>
                                </div>
                                <div class="container_item_info_01"></div>
                            </div>

                            <!-- ---- -->
                            <div class="container_item_cont_list">
                                <div class="container_item_photo_box_01">
                                    <a href="#">
                                        <div class="mot01"></div>
                                    </a>
                                </div>
                                <div class="container_item_info_01"></div>

                                <div class="container_item_photo_box_01">
                                    <a href="#">
                                        <div class="mot01"></div>
                                    </a>
                                </div>
                                <div class="container_item_info_01"></div>

                                <div class="container_item_photo_box_01">
                                    <a href="#">
                                        <div class="mot01"></div>
                                    </a>
                                </div>
                                <div class="container_item_info_01"></div>
                            </div>

                            <!-- ------ -->

                            <div class="container_item_cont_list">
                                <div class="container_item_photo_box_01">
                                    <a href="#">
                                        <div class="mot01"></div>
                                    </a>
                                </div>
                                <div class="container_item_info_01"></div>

                                <div class="container_item_photo_box_01">
                                    <a href="#">
                                        <div class="mot01"></div>
                                    </a>
                                </div>
                                <div class="container_item_info_01"></div>

                                <div class="container_item_photo_box_01">
                                    <a href="#">
                                        <div class="mot01"></div>
                                    </a>
                                </div>
                                <div class="container_item_info_01"></div>
                            </div>
                            
                            
                               
                            
                        </li>
                    </ul>
                    <ul class="container_item_title_control">
                        <li class="container_item_info_title">
                            <span class="container_item_info_title01">분위기 좋은</span>
                            <span class="container_item_info_title02">분위기 좋은</span>
                            <span class="container_item_info_title03">분위기 좋은</span>
                        </li>
                    </ul>
                    <ul class="container_item_title_control_2">
                        <li class="container_item_info_title_2">
                            <span class="container_item_info_title01_2">분위기 좋은</span>
                            <span class="container_item_info_title02_2">분위기 좋은</span>
                            <span class="container_item_info_title03_2">분위기 좋은</span>
                        </li>
                    </ul>

                    <ul class="container_item_title_control_3">
                        <li class="container_item_info_title_3">
                            <span class="container_item_info_title01_3">분위기 좋은</span>
                            <span class="container_item_info_title02_3">분위기 좋은</span>
                            <span class="container_item_info_title03_3">분위기 좋은</span>
                        </li>
                    </ul>
                </div>
            
            </div>
        </div>
      <footer class="footer">
        <div>Basic Board</div>
        <div>@ 2019 wonhui Park</div>
      </footer>
    
    </div>
</body>
</html>

templates/header.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}

<!-- header -->
<header id="header">
    <div class="header-inner">
        <h1 id="logo">
            <a href="/">
                <span class="blind">COFFLX</span>
                <img src="{% static 'posts/images/logo-2.png' %}" alt="logo">
            </a>
        </h1>
        <!-- search -->
        <div id="search" style="display: none;">
            <form id="search-form" class="search-form" action="" method="get">
                <fieldset>
                    <legend class="blind">검색</legend>
                    <div class="search-window">
                        <input id="query" name="query" type="text" title="검색어 입력" maxlength="255" class="input-text" placeholder="검색">
                        <button id="search-btn" type="submit" title="검색" class="btn-submit">
                            <span class="blind">검색</span>
                        </button>
                    </div>
                </fieldset>
            </form>
        </div>
        <!-- !search -->
        <nav id="gnb">
            <div class="gnb-inner">
                <ul class="list-nav">
                    <li class="nav-item">

                        {% if user.is_authenticated %}
                        <a href="{% url 'posts:host' %}" class="nav">
                        {% else %}
                        <a href="{% url 'accounts:login' %}" class="nav">
                        {% endif %}
                            <span class="nav-text">업체등록하기</span>
                        </a>
                    </li>
                    <li class="nav-item mr8" style="display: none;">
                        <button class="nav">
                            <div class="nav-img">
                                <img src="https://i.pinimg.com/474x/a3/a6/a0/a3a6a020c91a24f4d44fc154d9f68db9.jpg">
                            </div>
                        </button>
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <button class="nav item-box">
                            <div class="ham">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 28 28">
                                    <path fill="#0F0F14" fill-rule="evenodd" d="M2 8h24V6H2v2zm0 7h24v-2H2v2zm0 7h16v-2H2v2z"/>
                                </svg>
                            </div>
                            <div class="profile">
                                <svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 26">
                                    <defs>
                                        <style>
                                            .cls-1 { fill: #626974; }
                                        </style>
                                    </defs>
                                    <path class="cls-1" d="M16,13.36a5.35,5.35,0,1,0-5,0,9.46,9.46,0,0,0-6.92,9.09V23H22.93v-.5A9.46,9.46,0,0,0,16,13.36ZM9.14,8.68A4.35,4.35,0,1,1,13.57,13h-.16A4.35,4.35,0,0,1,9.14,8.68ZM5.06,22A8.47,8.47,0,0,1,13.4,14h.17A8.46,8.46,0,0,1,21.91,22Z"/>
                                </svg>
                            </div>
                        </button>
                        <!-- accounts -->
                        <div class="accounts-wrap" style="display: none;">
                            <div class="accounts-list">
                                <div class="accounts-item">
                                    <div class="my-name">{{user.username}}</div>
                                    <a href="#" class="my-cafe">
                                        카페관리
                                    </a>
                                </div>
                                <form action="{% url 'accounts:logout' %}" method="POST" class="accounts-item">
                                  {% csrf_token %}
                                  <button type="submit" class="btn btn-primary logout-btn">로그아웃</button>
                                </form>
                            </div>
                        </div>
                        <!-- !accounts -->
                        {% else %}
                        <a href="{% url 'accounts:login' %}" class="nav">
                            <span class="nav-text">로그인</span>
                        </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>
<!-- !header -->