accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
		path('signup/', views.signup, name='signup'),
		path('login/', views.login, name='login'),
        path('logout/', views.logout, name='logout'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.main, name='main'),
    path('host/', views.host, name='host'),
    path('regist/', views.regist, name='regist'),
    path('lists/', views.lists, name='lists'),
    path('<int:cafe_id>/', views.detail, name='detail'),
    path('image/', views.image, name='image'),
    path('rcmd/', views.rcmd, name='rcmd'),
    path('create/', views.create, name='create'),
    path('<int:cafe_id>/review', views.review, name='review'),
    path('mypage/', views.mypage, name='mypage'),
    path('like/<int:cafe_id>/',views.like, name='like'),
    path('mark/<int:cafe_id>/',views.mark, name="mark"),
    path('mypage/markedcafe/', views.marked_cafe, name='markedcafe'),
    path('mypage/mysetting/', views.mysetting, name='mysetting'),
    path('mypage/version/', views.version, name='version'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=20, null=True)

    def __str__(self):
        return f'{self.name}'


class Cafe(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=20, null=True)
    address = models.CharField(max_length=100, null=True)
    open_time = models.TimeField(null=True)
    close_time = models.TimeField(null=True)
    holiday = models.CharField(max_length=50, null=True)
    tel = models.CharField(max_length=50, null=True)
    tags = models.ManyToManyField(Tag)
    memo = models.TextField(null=True)

    liked_users = models.ManyToManyField(User, related_name='like_cafe', blank=True)
    marked_users = models.ManyToManyField(User, related_name="marked_cafe", blank=True)


    def __str__(self):
        return f'{self.name}: {self.address}: {self.open_time}: {self.close_time}: {self.holiday}: {self.tel}'


class Image(models.Model):
    cafe = models.ForeignKey(Cafe, on_delete=models.CASCADE, null=False)
    image = models.ImageField(upload_to='posts', null=True)

posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.serializers import serialize
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from .models import Cafe, Tag, Image
from django.views.generic.base import View
from urllib.parse import urlparse
import json
import requests
import datetime
 
# 카카오 API 맵 
def getLatLng(address):
    result = ""
 
    url = 'https://dapi.kakao.com/v2/local/search/address.json?query=' + address
    rest_api_key = 'd975e180da8e3f1265e42a90c8ca1875'
    header = {'Authorization': 'KakaoAK ' + rest_api_key}
 
    r = requests.get(url, headers=header)
 
    if r.status_code == 200:
        result_address = r.json()["documents"][0]["address"]
        
        result = result_address["y"], result_address["x"]
    else:
        result = "ERROR[" + str(r.status_code) + "]"
    
    return result
 
 
def getKakaoMapHtml(address_latlng):
    javascript_key = "45522189c1ececf745d0f4c8c482b82e"
 
    result = ""
    result = result + "<div id='map' style='width:300px;height:200px;display:inline-block;'></div>" + "\n"
    result = result + "<script type='text/javascript' src='//dapi.kakao.com/v2/maps/sdk.js?appkey=" + javascript_key + "'></script>" + "\n"
    result = result + "<script>" + "\n"
    result = result + "    var container = document.getElementById('map'); " + "\n"
    result = result + "    var options = {" + "\n"
    result = result + "           center: new kakao.maps.LatLng(" + address_latlng[0] + ", " + address_latlng[1] + ")," + "\n"
    result = result + "           level: 3" + "\n"
    result = result + "    }; " + "\n"
    result = result + "    var map = new kakao.maps.Map(container, options); " + "\n"
    
    # 검색한 좌표의 마커 생성을 위해 추가
    result = result + "    var markerPosition  = new kakao.maps.LatLng(" + address_latlng[0] + ", " + address_latlng[1] + ");  " + "\n"
    result = result + "    var marker = new kakao.maps.Marker({position: markerPosition}); " + "\n"
    result = result + "    marker.setMap(map); " + "\n"
 
    result = result + "</script>" + "\n"
    
    return result
 
# main()
if __name__ == "__main__":
    address = "서울 강남구 선릉로 669"
    
    # 카카오 REST API로 좌표 구하기
    address_latlng = getLatLng(address)
 
    # 좌표로 지도 첨부 HTML 생성
    if str(address_latlng).find("ERROR") < 0:
        map_html = getKakaoMapHtml(address_latlng)
        
        print(map_html)
    else:
        print("[ERROR]getLatLng")




#-------------------------카카오맵--------------------
 

def main(request):
    total = Cafe.objects.annotate(num_tags=Count('tags')).filter(num_tags__gt=1).count()
    cafes = Cafe.objects.annotate(num_tags=Count('tags')).filter(num_tags__gt=1).order_by('-num_tags', 'id')[:4]
    context = {
        'total': total,
        'cafes': cafes,
        'tab': 'home',
    }
    return render(request, 'posts/main.html', context)


def rcmd(request):
    num = int(request.GET['num']) - 1
    offset = int(request.GET['offset'])
    cafes = Cafe.objects.annotate(num_tags=Count('tags')).filter(num_tags__gt=1).order_by('-num_tags', 'id')[num: num + offset]
    if cafes:
        cafes = serialize('json', cafes)
        cafes = json.loads(cafes)
        cafes = list(map(lambda cafe: {'id': cafe["pk"], **cafe["fields"]}, cafes))
        context = {
            'result': True,
            'cafes': cafes,
        }
    else:
        context = { 'result': False }
    return HttpResponse(json.dumps(context), content_type="application/json")


def host(request):
    return render(request, 'posts/host.html')


def regist(request):
    name = request.POST['name']
    tel = request.POST['tel']
    address = request.POST['address'] + ' ' + request.POST['detailAddress']
    ot = datetime.time(hour=int(request.POST['openTime']))
    ct = datetime.time(hour=int(request.POST['closeTime']))
    holiday = request.POST['holiday']
    body = request.POST['body']
    cafe = Cafe(name=name, memo=body, address=address, open_time=ot, close_time=ct, holiday=holiday, tel=tel)
    cafe.save()

    if 'image[]' in request.FILES:
        images = request.FILES.getlist('image[]')
        for image in images:
            img = Image(cafe=cafe, image=image)
            img.save()

    tags = request.POST['tags'].split(",")
    if len(tags) > 0 and tags[0]:
        for tag in tags:
            taged = Tag.objects.filter(name=tag).first()
            cafe.tags.add(taged.id)

    return redirect('posts:main')


def lists(request):

    page = 1
    offset = 4

    if 'page' in request.GET.keys():
        page = int(request.GET['page'])

    if 'offset' in request.GET.keys():
        offset = int(request.GET['offset'])

    num = (page - 1) * offset

    keywords = []

    if 'keywords[]' in request.GET.keys():
        keywords = request.GET.getlist('keywords[]')

        keyword = keywords.pop()
        cafes = Cafe.objects.filter(tags__name=keyword)

        for keyword in keywords:
            cafes = cafes.filter(tags__name=keyword)

        cafes = cafes.order_by('-id')[num: num + offset]
    else:
        cafes = Cafe.objects.all().order_by('-id')[num: num + offset]

    if request.is_ajax():
        cafes = serialize('json', cafes)
        cafes = json.loads(cafes)
        cafes = list(map(lambda cafe: {'id': cafe["pk"], **cafe["fields"]}, cafes))
        return HttpResponse(json.dumps({"cafes": cafes, "user": request.user.pk}), content_type="application/json")

    return render(request, 'posts/lists.html', {"cafes": cafes, 'tab': 'search'})

def detail(request, cafe_id):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    try:
        cafe = Cafe.objects.get(id=cafe_id)

        return render(request, 'posts/m-detail.html', { "cafe": cafe })

    except Cafe.DoesNotExist:
        pass

    return redirect('posts:lists')


def image(request):
    cafe = request.GET['cafe']
    
    if 'main' in request.GET.keys():
        image = Image.objects.filter(cafe=cafe).first()
        if image:
            imageurl = image.image.url
        return HttpResponse(json.dumps({"image": imageurl}), content_type="application/json")
    
    images = Image.objects.filter(cafe=cafe)
    if images:
        imageurls = []
        for image in images:
            imageurls.append(image.image.url)
    return HttpResponse(json.dumps({"images": imageurls}), content_type="application/json")


def review(request, cafe_id):
    return render(request, 'posts/review.html')

def create(request):
    return redirect('posts:main')

def mypage(request):
    return render(request, 'posts/mypage.html', {'tab': 'profile'})

def marked_cafe(request):
    # cafes = []
    cafes = request.user.marked_cafe.all()
    
    return render(request, 'posts/mypage/markedcafe.html', { "cafes": cafes })

def mysetting(request):
    return render(request, 'posts/mypage/mysetting.html')

def version(request):
    return render(request, 'posts/mypage/version.html')


@login_required
def like(request, cafe_id):

    try:
        cafe = Cafe.objects.get(id=cafe_id)

        if request.user in cafe.liked_users.all():
            cafe.liked_users.remove(request.user)
        else:
            cafe.liked_users.add(request.user)
            
        if 'next' in request.GET.keys():
            next = request.GET['next']
            return redirect(next)

        return redirect('posts:detail', cafe_id=cafe.id)

    except Cafe.DoesNotExist:
        pass

    return redirect('posts:main')

@login_required
def mark(request, cafe_id):

    try:
        cafe = Cafe.objects.get(id=cafe_id)

        if request.user in cafe.marked_users.all():
            cafe.marked_users.remove(request.user)
        else:
            cafe.marked_users.add(request.user)

        if 'next' in request.GET.keys():
            next = request.GET['next']
            return redirect(next)

        return redirect('posts:detail', cafe_id=cafe.id)

    except Cafe.DoesNotExist:
        pass

    return redirect('posts:main')

posts/templates/posts/detail.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/header.css' %}">
<!-- reset.css     -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reset-css@4.0.1/reset.min.css" />
<!-- normalize.css -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" />
<!-- 사용자 스타일 -->
    <link rel="stylesheet" href="{% static 'posts/css/detail.css' %}" />
{% endblock %}
{% block header %}
{% include "header.html" %}
{% endblock %}
{% block content %}
{% if cafe %}
    <!-- Container_1 -->
    <div class="container_1">
        <div class="container_img">
            <ul class="container_img_control">
                {% for img in cafe.image_set.all|slice:":5" %}
                <li class="container_img_bg" style="background-image: url({{ img.image.url }})">
                    <a href="{{ img.image.url }}"></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <!-- Container_2 -->
    <div class="container_2">
        <div class="container_2_control">
            <div class="container_2_mainfont">
                {{ cafe.name }}<span class="container_2_mainnumber">4.5</span>
            </div>
            <div class="container_2_review_img">
                <div class="container_2_review_icon">
                    <span class="container_2_review_icon_font">리뷰쓰기</span>
                </div>
                <div class="container_2_review_icon">
                    <span class="container_2_star_icon_font">가고싶다</span>
                </div>
                <div class="container_2_icon_control">
                    <div class="container_2_icon_pencil"></div>
                    <div class="container_2_icon_star"></div>
                </div>
                <div class="container_2_icon_control2">
                    <div class="container_2_icon_move">
                        <div class="container_2_icon_eye">눈</div>
                        <div class="container_2_icon_pencil_2">연필</div>
                        <div class="container_2_icon_star_2">별</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container_2_bottomline"></div>
    <!-- Table -->
<tbody>
    <div class="main_table">
        <div class="main_table_control">
            <tr class="main_table_1">
                <th class="informaiton_address-1">주소</th>
                <td class="informaiton_address_control-1">
                    <span id="cafeAddress" class="informaiton_address_font-1">{{ cafe.address }}<br></span>
                </td>
            </tr>
        </div>
        <div class="main_table_control_2">
            <tr class="main_table_2">
                <th class="informaiton_telephone-2">전화번호</th>
                <td class="informaiton_telephone_control-2">
                    <span class="informaiton_telephone_1-1">{{ cafe.tel }}</span>
                </td>
            </tr>
        </div>
        <div class="main_table_control_3">
            <tr class="main_table_3">
                <th class="informaiton_category-3">카테고리</th>
                <td class="informaiton_category_control-3">
                    <span class="informaiton_category_1-1">
                        {{ cafe.tags.all|join:" ・ " }}
                    </span>
                </td>
            </tr>
        </div>
        <div class="main_table_control_6">
            <tr class="main_table_6">
                <th class="informaiton_opentime-6">영업시간</th>
                <td class="informaiton_opentime_control-6">
                    <span class="informaiton_opentime_1-1">{{ cafe.open_time }} ~ {{ cafe.close_time }}</span>
                </td>
            </tr>
        </div>
        <div class="main_table_control_8">
            <tr class="main_table_8">
                <th class="informaiton_holiday-8">휴일</th>
                <td class="informaiton_holiday_control-8">
                    <span class="informaiton_holiday_1-1">{{ cafe.holiday }}</span>
                </td>
            </tr>
        </div>
    </div>
</tbody>
    <!-- Table end-->     
    <div class="table_bottomline"></div>

    <!-- Start container_3 -->
    <div class="container_3">
        <ul class="container_3_review_menu">
            <li class="container_3_review_list">
                <span class="container_3_review_review_1">리뷰</span>
                <span class="container_3_review_tuple_1">(45)</span>
            </li>
        </ul>
        <ul class="container_3_review_evaluation">
            <li class="container_3_evaluation_list">
                <span class="container_3_evaluation_list_1">전체</span>
                <span class="container_3_evaluation_tuple_1">(45)</span>
            </li>
        </ul>
        <ul class="container_3_review_good">
            <li class="container_3_good_list">
                <span class="container_3_good_list_1">맛있다</span>
                <span class="container_3_good_tuple_1">(35)</span>
            </li>
        </ul>
        <ul class="container_3_review_fine">
            <li class="container_3_fine_list">
                <span class="container_3_fine_list_1">괜찮다</span>
                <span class="container_3_fine_tuple_1">(10)</span>
            </li>
        </ul>
        <ul class="container_3_review_soso">
            <li class="container_3_soso_list">
                <span class="container_3_soso_list_1">별로</span>
                <span class="container_3_soso_tuple_1">( 5 )</span>
            </li>
        </ul>
    </div>
    <!-- End container_3 -->
    <!-- Start_container_4 -->
    <section class="container_4">
        <header class="container_4_header">
            <div class="container_4_cafe_review_img"></div>
            <div class="container_4_cafe_review_img_font">chef.kang</div>
            <div class="container_4_cafe_review_img_pencil">
                <span class="container_4_cafe_review_img_pencil_font">200</span>
            </div>
            <div class="container_4_cafe_review_img_star">
                <span class="container_4_cafe_review_img_star_font">116</span>
            </div>
            <!-- ---------------------------------------------------------->
            <div class="container_4_date">
                <span class="container_4_date_font">2020-08-11</span>                
            </div>
            <span class="container_4_review_font">로우커피스텐드 직원들 친절하고<br>커피 너무 맛있다 <br> 주택사시에 협소한곳에 있음ㅋ~</span>
            <div class="container_4_review_icon"></div>
            <span class="container_4_review_icon_font">맛있다 </span>
            <!-- -------------------------------------------------------------- -->
            <ul class="container_4_review_img_list">
                <li class="container_4_review_img_con">
                    <div class="container_4_review_img__01"></div>
                    <div class="container_4_review_img__02"></div>
                    <div class="container_4_review_img__03"></div>                   
                </li>
            </ul>
        </header>
    </section>
    <div class="table_bottomline01"></div>
    
     <!-- Start Container_4_1   -->
    <section class="container_4_1">
        <header class="container_4_header_1">
            <div class="container_4_cafe_review_img_1"></div>
            <div class="container_4_cafe_review_img_font_1">chef.kang</div>
            <div class="container_4_cafe_review_img_pencil_1">
                <span class="container_4_cafe_review_img_pencil_font_1">200</span>
            </div>
            <div class="container_4_cafe_review_img_star_1">
                <span class="container_4_cafe_review_img_star_font_1">116</span>
            </div>
            <!-- ---------------------------------------------------------->
            <div class="container_4_date_1">
                <span class="container_4_date_font_1">2020-08-11</span>                
            </div>
            <span class="container_4_review_font_1">로우커피스텐드 직원들 친절하고<br>커피 너무 맛있다 <br> 주택사시에 협소한곳에 있음ㅋ~</span>
            <div class="container_4_review_icon_1"></div>
            <span class="container_4_review_icon_font_1">맛있다 </span>
            <!-- -------------------------------------------------------------- -->
            <ul class="container_4_review_img_list_1">
                <li class="container_4_review_img_con_1">
                    <div class="container_4_review_img__01_1"></div>
                    <div class="container_4_review_img__02_1"></div>
                    <div class="container_4_review_img__03_1"></div>                   
                </li>
            </ul>
        </header>
    </section>
            <!-- 지도를 표시할 div -->
            <div id='map' style='width:300px;height:200px;display:inline-block;'></div>
            
            <script type='text/javascript' src='//dapi.kakao.com/v2/maps/sdk.js?appkey=a0d20539b358c5001f3cb48bc15ce08b&libraries=services'></script>
            <script>
                var address = document.getElementById("cafeAddress").innerText;
                // console.log(address);

                var container = document.getElementById('map');  // 지도를 표시할 div
                var options = {
                        center: new kakao.maps.LatLng(37.5166119773031, 127.041258693516),  // 지도의 중심좌표
                        level: 3  // 지도 확대 레벨
                };
                // 지도를 표시할 div 와 지도 옵션으로 지도 생성
                var map = new kakao.maps.Map(container, options);

                // 주소-좌표 변환 객체를 생성합니다
                var geocoder = new kakao.maps.services.Geocoder();

                // 주소로 좌표를 검색합니다
                geocoder.addressSearch(address, function(result, status) {

                    // 정상적으로 검색이 완료됐으면 
                     if (status === kakao.maps.services.Status.OK) {

                        var coords = new kakao.maps.LatLng(result[0].y, result[0].x);
                         console.log(coords);

                        // 결과값으로 받은 위치를 마커로 표시합니다
                        var marker = new kakao.maps.Marker({
                            map: map,
                            position: coords
                        });

                        // 인포윈도우로 장소에 대한 설명을 표시합니다
                        var infowindow = new kakao.maps.InfoWindow({
                            content: '<div style="width:150px;text-align:center;padding:6px 0;">{{ cafe.name }}</div>'
                        });
                        infowindow.open(map, marker);

                        // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
                        map.setCenter(coords);
                    } 
                });
            </script>
{% else %}
No Cafe.
{% endif %}
{% endblock %}

posts/templates/posts/m-detail.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/header.css' %}">
<link rel="stylesheet" href="{% static 'posts/css/m-detail.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css" />
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
{% endblock %}
{% block script %}
<script src="{% static 'posts/js/detail.js' %}"></script>
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
{% endblock %}
{% block content %}
<div id="container">
    {% block header %}
    {% include "header.html" %}
    {% endblock %}
    {% if cafe %}
    <div class="intro-wrap">
        <div class="top-contents">
            <div class="back">
                <a href="javascript:history.back();">나가기</a>
            </div>
        </div>
        <!-- Slider main container -->
        <div class="swiper-container">
          <!-- Additional required wrapper -->
          <div class="swiper-wrapper">
            <!-- Slides -->
            {% for img in cafe.image_set.all %}
                <a class="swiper-slide" data-fancybox="images" href="{{ img.image.url }}"><img src="{{ img.image.url }}"></a>
            {% endfor %}
          </div>
        </div>
        <div class="intro-box">
            <div class="intro">
                <div class="cafe-name">
                    <dl class="intro-dl">

                        <div class="intro-table">
                            <div class="like-box">
                                
                                {% if user.is_authenticated %}
                                    <form action="{% url 'posts:like' cafe.id %}" method="POST">
                                        {% csrf_token %}

                                        {% if user in cafe.liked_users.all %}
                                            <button type="submit" class="btn-like">
                                                <img src="{% static 'posts/images/icon/liked.png' %}">
                                            </button>
                                        {% else %}
                                            <button type="submit" class="btn-like">
                                                <img src="{% static 'posts/images/icon/like.png' %}">
                                            </button>
                                        {% endif %}
                                    </form>
                                {% endif %}


                                <div class="btn-reply">
                                    <img src="{% static 'posts/images/icon/talkbubble.png' %}">
                                </div>   
                                
                                
                              <!-- If we need pagination -->
                              <div class="swiper-pagination cafe-img-list"></div>
                            
                            
                                <div class="btn-bookmark">

                                    {% if user.is_authenticated %}
                                        <form action="{% url 'posts:mark' cafe.id %}" method="POST">
                                            {% csrf_token %}

                                            {% if user in cafe.marked_users.all %}
                                                <button type="submit" class="btn-like">
                                                    <img src="{% static 'posts/images/icon/marked.png' %}">
                                                </button>
                                            {% else %}
                                                <button type="submit" class="btn-like">
                                                    <img src="{% static 'posts/images/icon/mark.png' %}">
                                                </button>
                                            {% endif %}
                                        </form>
                                     {% endif %}
                                </div>   
                            </div>

                            <div> <a class="like-number">가보고싶어요</a> {{ cafe.liked_users.count }} <a class="like-number">개</a></div>

                        </div>
                        <dt>{{ cafe.name }}</dt>
                    </dl>
                </div>
                <div class="cafe-area">
                    <p id="cafeAddress">
                        {{ cafe.address }}
                    </p>
                </div>
            </div>
        </div>
    </div>    
    <!-- 지도를 표시할 div -->
    <div class="map-wrap">
        <a id="mapLink" href="https://map.kakao.com/link/map/37.402056,127.108212" target="_blank">
            <div id='map'></div>
        </a>
    </div>
    <div class="detail-wrap">
        <p>
            <span>전화</span>
            {{ cafe.tel }}
        </p>
        <p>
            <span>카테고리</span>
            {{ cafe.tags.all|join:" ・ " }}
        </p>
        <p>
            <span>영업시간</span>
            {{ cafe.open_time }} ~ {{ cafe.close_time }}
        </p>
        <p>
            <span>휴일</span>
            {{ cafe.holiday }}
        </p>
    </div>
    
    <script type="module">
      import Swiper from 'https://unpkg.com/swiper/swiper-bundle.esm.browser.min.js'

      const swiper = new Swiper('.swiper-container', {
          slidesPerView: 'auto',
          // Optional parameters
          direction: 'horizontal',
          // loop: true,

          // If we need pagination
          pagination: {
            el: '.swiper-pagination',
          },

          // Navigation arrows
          navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
          },

          // And if we need scrollbar
          scrollbar: {
            el: '.swiper-scrollbar',
          },
        });
    </script>

    <script type='text/javascript' src='//dapi.kakao.com/v2/maps/sdk.js?appkey=a0d20539b358c5001f3cb48bc15ce08b&libraries=services'></script>
    <script>
        var address = document.getElementById("cafeAddress").innerText;
        // console.log(address);
        
        var mapLink = document.getElementById('mapLink');
        var container = document.getElementById('map');  // 지도를 표시할 div
        var options = {
                center: new kakao.maps.LatLng(37.5166119773031, 127.041258693516),  // 지도의 중심좌표
                level: 3  // 지도 확대 레벨
        };
        // 지도를 표시할 div 와 지도 옵션으로 지도 생성
        var map = new kakao.maps.Map(container, options);
        
        map.setZoomable(false);
        map.setDraggable(false);
        
        // 주소-좌표 변환 객체를 생성합니다
        var geocoder = new kakao.maps.services.Geocoder();

        // 주소로 좌표를 검색합니다
        geocoder.addressSearch(address, function(result, status) {

            // 정상적으로 검색이 완료됐으면 
             if (status === kakao.maps.services.Status.OK) {

                var coords = new kakao.maps.LatLng(result[0].y, result[0].x);
                 console.log(coords);
                 
                 mapLink.setAttribute('href', 'https://map.kakao.com/link/map/{{ cafe.name }},' + result[0].y + ',' + result[0].x);

                // 결과값으로 받은 위치를 마커로 표시합니다
                var marker = new kakao.maps.Marker({
                    map: map,
                    position: coords
                });

                // 인포윈도우로 장소에 대한 설명을 표시합니다
                var infowindow = new kakao.maps.InfoWindow({
                    content: '<div style="width:150px;text-align:center;padding:6px 0;">{{ cafe.name }}</div>'
                });
                infowindow.open(map, marker);

                // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
                map.setCenter(coords);
            } 
        });
    </script>
    {% else %}
    없음
    {% endif %}
</div>
{% endblock %}

posts/templates/posts/mypage.html
{% extends "base.html" %}
{% load static %}
{% load socialaccount %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'posts/css/mypage.css' %}">
{% endblock %}
{% block content %}
    
    {% block header %}
    {% include "header.html" %}
    {% endblock %}

    {% csrf_token %}
    {% if user.is_authenticated %}

    <div class="mypage-wrap">

        <section class="mypage">
            <div class="profile">
                <img src="{% static 'posts/images/icon/user.png' %}">
                <div class="profile-name">{{user.username}}님</div>
            </div>
            <hr>
            
            <h1>내 정보</h1>
            <hr>
            
            <div>
                <div class="box">
                    <div class="mycafe">가고싶은 카페</div>
                        <a href="{% url 'posts:markedcafe' %}" class="mypage-icon">
                        <img src="{% static 'posts/images/icon/marked.png' %}">
                        </a>
                </div>   
                
                <div class="box">
                    <div class="mycafe">리뷰남긴 카페</div>
                        <button type="button" class="mypage-icon">
                        <img src="{% static 'posts/images/icon/hotcoffee.png' %}">
                        </button>
                </div>
                
                <div class="box">
                    <div class="mycafe">설정</div>
                        <a href="{% url 'posts:mysetting' %}" class="mypage-icon">
                        <img src="{% static 'posts/images/icon/settings.png' %}">
                        </a>
                </div>
            </div>    

        </section>
    </div>

    {% else%}
    <script type="text/javascript">
        alert('먼저 로그인을 해주세요.');
        window.location.href = "{% url 'accounts:login' %}";
    </script>

    {% endif %}
{% endblock %}